# Generated by Django 5.2 on 2025-04-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_change_description', 'Can change description'), ('can_change_category', 'Can change category'), ('can_change_is_published', 'Can change is_published')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
